# Generated by Django 6.1.1 on 2026-09-14 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calendrier', '0001_initial'),
        ('cultures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendrieragricole',
            name='culture_suivie',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendrier', to='cultures.culturesuivie'),
        ),
        migrations.AddField(
            model_name='operationagricole',
            name='calendrier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='calendrier.calendrieragricole'),
        ),
        migrations.AddField(
            model_name='stade',
            name='culture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stades', to='cultures.cultureref'),
        ),
        migrations.AddField(
            model_name='operationagricole',
            name='stade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='calendrier.stade'),
        ),
    ]
