# Generated by Django 6.1.1 on 2026-09-21 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendrier', '0002_initial'),
        ('cultures', '0005_referentielagronomique'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operationagricole',
            options={'ordering': ['date_debut', 'id']},
        ),
        migrations.RemoveField(
            model_name='stade',
            name='kc',
        ),
        migrations.AddField(
            model_name='stade',
            name='date_debut',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stade',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='operationagricole',
            name='stade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='calendrier.stade'),
        ),
        migrations.AlterField(
            model_name='stade',
            name='culture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stades_calcul', to='cultures.cultureref'),
        ),
        migrations.AlterField(
            model_name='stade',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='StadeReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('ordre', models.PositiveIntegerField()),
                ('duree_jours', models.PositiveIntegerField()),
                ('kc', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('description', models.TextField(blank=True)),
                ('referentiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stades', to='cultures.referentielagronomique')),
            ],
            options={
                'ordering': ['referentiel_id', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='RegleOperationAgricole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('declencheur', models.CharField(choices=[('semis', 'Date de semis'), ('debut_stade', 'Début du stade'), ('fin_stade', 'Fin du stade'), ('fin_cycle', 'Fin du cycle')], max_length=30)),
                ('decalage_jours', models.IntegerField(default=0)),
                ('duree_jours', models.PositiveIntegerField(default=1)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regles_operations', to='cultures.cultureref')),
                ('stade_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regles_operations', to='calendrier.stadereference')),
            ],
            options={
                'ordering': ['culture_id', 'ordre', 'id'],
            },
        ),
        migrations.AddField(
            model_name='stade',
            name='reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stades_calcules', to='calendrier.stadereference'),
        ),
        migrations.AddConstraint(
            model_name='stadereference',
            constraint=models.UniqueConstraint(fields=('referentiel', 'ordre'), name='unique_ordre_stade_referentiel'),
        ),
    ]
