# Generated by Django 6.1.1 on 2026-09-21 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendrier', '0003_alter_operationagricole_options_remove_stade_kc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stade',
            name='reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stades_calcules', to='calendrier.stadereference'),
        ),
    ]
