# Generated by Django 6.1.1 on 2026-09-14 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cultures', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='culturesuivie',
            name='agriculteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cultures_suivies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='culturesuivie',
            name='commune',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cultures.communelocalite'),
        ),
        migrations.AddField(
            model_name='culturesuivie',
            name='culture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suivis', to='cultures.cultureref'),
        ),
        migrations.AddField(
            model_name='culturesuivie',
            name='departement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cultures.departement'),
        ),
        migrations.AddField(
            model_name='communelocalite',
            name='departement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communes', to='cultures.departement'),
        ),
        migrations.AddField(
            model_name='departement',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departements', to='cultures.region'),
        ),
        migrations.AddField(
            model_name='culturesuivie',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cultures.region'),
        ),
        migrations.AlterUniqueTogether(
            name='communelocalite',
            unique_together={('departement', 'nom')},
        ),
        migrations.AlterUniqueTogether(
            name='departement',
            unique_together={('region', 'nom')},
        ),
    ]
