# Generated by Django 6.1.1 on 2026-09-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultures', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='communelocalite',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='communelocalite',
            name='type_localite',
            field=models.CharField(blank=True, choices=[('commune', 'Commune'), ('arrondissement_ville', 'Commune / Arrondissement / Ville'), ('quartier_village_hameau', 'Quartier / Village / Hameau')], max_length=40, null=True),
        ),
        migrations.AddConstraint(
            model_name='communelocalite',
            constraint=models.UniqueConstraint(fields=('departement', 'nom', 'type_localite'), name='unique_localite_par_departement_type'),
        ),
    ]
