# Generated by Django 6.1.1 on 2026-09-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultures', '0003_alter_communelocalite_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communelocalite',
            name='type_localite',
            field=models.CharField(choices=[('commune', 'Commune'), ('arrondissement_ville', 'Commune / Arrondissement / Ville'), ('quartier_village_hameau', 'Quartier / Village / Hameau')], max_length=40),
        ),
    ]
