# Generated by Django 6.1.1 on 2026-09-21 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultures', '0004_alter_communelocalite_type_localite'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferentielAgronomique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_cycle', models.CharField(choices=[('annuelle', 'Annuelle'), ('perenne', 'Pérenne')], default='annuelle', max_length=20)),
                ('cycle_min_jours', models.PositiveIntegerField(blank=True, null=True)),
                ('cycle_max_jours', models.PositiveIntegerField(blank=True, null=True)),
                ('besoin_eau_min_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('besoin_eau_max_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('sensibilite_secheresse', models.CharField(choices=[('faible', 'Faible'), ('faible_moyenne', 'Faible à moyenne'), ('moyenne', 'Moyenne'), ('moyenne_forte', 'Moyenne à forte'), ('forte', 'Forte')], default='moyenne', max_length=30)),
                ('source', models.CharField(choices=[('FAO', 'FAO'), ('ISRA', 'ISRA'), ('ANSD', 'ANSD'), ('DAPSA', 'DAPSA'), ('AFRICARICE', 'AfricaRice'), ('AUTRE', 'Autre')], max_length=30)),
                ('source_reference', models.CharField(blank=True, max_length=255)),
                ('source_url', models.URLField(blank=True)),
                ('zone_agroecologique', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('valide', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('culture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referentiel_agronomique', to='cultures.cultureref')),
            ],
        ),
    ]
