# Generated by Django 6.1.1 on 2026-09-14 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cultures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonneeMeteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure', models.DateTimeField()),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('humidite', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vent_kmh', models.DecimalField(decimal_places=2, max_digits=6)),
                ('precipitation_mm', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('probabilite_pluie', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('source', models.CharField(default='demo', max_length=60)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meteo', to='cultures.communelocalite')),
            ],
        ),
        migrations.CreateModel(
            name='ConsultationMeteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creee_le', models.DateTimeField(auto_now_add=True)),
                ('culture_suivie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations_meteo', to='cultures.culturesuivie')),
                ('donnee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meteo.donneemeteo')),
            ],
        ),
    ]
