# Generated by Django 6.1.1 on 2026-09-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyseIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_analyse', models.DateTimeField(auto_now_add=True)),
                ('probleme', models.CharField(blank=True, max_length=160)),
                ('confiance', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('resultat', models.TextField()),
                ('conseil', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ia/%Y/%m/')),
                ('date_prise', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
