# Generated by Django 6.1.1 on 2026-09-14 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cultures', '0002_initial'),
        ('ia', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='agriculteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos_ia', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='photo',
            name='culture_suivie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='cultures.culturesuivie'),
        ),
        migrations.AddField(
            model_name='analyseia',
            name='photo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analyse', to='ia.photo'),
        ),
    ]
